baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Bachs'
theme = 'rusty-typewriter'

[rusty_typewriter]
 [params.rtwt]
  sidePane = true
  countPageItems = 7 
 [params.rtwt.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5
 [params.rtwt.side.home]
  sidePaneSticky = false 
  taxonomies = ['tags']
  countTaxonomy = 5
 [params.rtwt.side.list]
  sidePaneSticky = false
 [params.rtwt.side.single]
  sidePaneSticky = true 
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

